---
title: "Introducción"
numbered: true
---

La crisis económica de la pandemia del COVID-19 es uno de los tantos
factores que producen que en el actual contexto eleccionario, la
cuestión del desarrollo económico se presente como eje fundamental del
debate político, presentándose en él un consenso general en torno a un
supuesto: la idea general de que las pequeñas y medianas empresas (en
adelante, PYMEs) portarían la capacidad de generar más empleo, mejorar
las condiciones laborales y subir los salarios con asistencia del
Estado, apareciendo como un agente dinamizador de la economía capaz de
producir un viraje en el paradigma económico “neoliberal” chileno (Núñez
et al., 2025), con un discurso emprendedurista y meritocrático.

Sin embargo la trayectoria histórica de la composición del trabajo en
Chile da luces de que las PYMEs portarían otra necesidad dentro del
encadenamiento productivo del país.

El contexto de fragmentación productiva (Iñigo Carrera, 2013), así como
el Plan Laboral y el resto de “contrarreformas” (Gárate, 2012)
económicas dictatoriales produjeron junto al desmoronamiento del Gran
Capital Industrial doméstico, la proliferación de pequeños capitales que
vendrían a tomar el rol de tercerizar la producción del Gran
Empresariado, externalizar riesgos mediante modalidades de subcontrato,
absorber los costos laborales, flexibilizar las relaciones de trabajo y
favorecer la informalidad, perpetuar los bajos salarios y ante todo,
obstruir que la organización laboral entre en conflicto directamente con
el Gran Capital (Ruiz, 2013).

Esta dispersión productiva no sólo reduce la capacidad efectiva de
negociación laboral, sino que también consolida una modalidad sustentada
en la extracción de una plusvalía extraordinaria por sobreexplotación
(Espro y Zorattani, 2012; Espro y Baez 2018), como medio para compensar
la baja productividad de las PYMEs.

Es por este contexto que el presente trabajo toma relevancia al ahondar
entorno a ese supuesto fundamental, mirando cómo el tamaño de la empresa
se ve relacionado con los tópicos fundamentales del debate público: el
salario, la formalidad y la organización laboral, buscando ver si existe
una diferenciación sustancial en el caso de las PYMEs.

## Conceptos clave

Los conceptos claves a trabajar serán el tamaño de empresa, el nivel de
organización laboral, el salario y la formalidad laboral. Con el fin de
caracterizar la composición de las PYMEs dentro del encadenamiento
productivo chileno.

El concepto central a tratar será el tamaño de la empresa, el cuál
comprendemos como la cantidad de trabajadores presentes en una empresa
dependiendo de su composición orgánica de su capital (Durán, 2024; Marx,
2010).

Esta puede verse influenciada por la inversión en capital variable o en
capital constante; y se relaciona directamente con los niveles de
organización laboral, formalidad y salario que puede soportar
dependiendo de su competitividad.

El presente trabajo busca analizar y cuantificar empíricamente la
relación entre el concepto de tamaño de la empresa, con los conceptos de
nivel de organización laboral, formalidad y el salario.

Entendemos por organización laboral, al conjunto de gremios, colegios de
profesores y sindicatos, que en un contexto de fragmentación productiva
y bajo el marco legal del Plan Laboral de 1979, la población ocupada se
ha visto obligada a tomar para poder articularse en defensa de sus
condiciones de trabajo (Ruiz, 2013).

Entendemos por salario, la remuneración por el gasto de fuerza de
trabajo invertido en la jornada destinado a la reproducción física y
psicológica de los trabajadores (Marx, 2010).

Entendemos por formalidad laboral a las condiciones contractuales que
posibilitan que se encuentre dentro de los márgenes de protección de la
legislación vigente y cotizar para los servicios previsionales de salud
y pensiones. En palabras de la Organización Internacional del Trabajo
(2015):

> "El empleo en la economía formal se caracteriza por estar
> reglamentado, es decir, que los trabajadores cuentan con protección
> legal y social. Esto incluye el reconocimiento de sus derechos
> laborales, como un salario mínimo, límites a la jornada de trabajo,
> condiciones de trabajo seguras, protección social (como pensiones y
> seguro de salud) y la libertad de afiliarse a sindicatos y negociar
> colectivamente." (OIT, 2015, p. xx).

En este sentido, investigaciones como las de Ruiz (2013) han mostrado en
caracterizar la relación entre la baja organización laboral, los bajos
salarios y la informalidad con empresas más pequeñas.

Este análisis se complementa con los hallazgos de Espro y Baez (2018),
que identifica la modalidad específica de las PYMEs en la dinámica de
acumulación de capital argentina como una orientada a la extracción de
una “plusvalía extraordinaria” por sobreexplotación.

**Objetivo general e hipótesis**

Este trabajo tiene como objetivo general mirar la relación del tamaño de
las empresas del país con los niveles de organización laboral, salario y
formalidad, para observar si existe evidencia como para afirmar que las
empresas más pequeñas toman un papel diferenciado en estos ámbitos.

A raíz de la revisión bibliográfica anterior, se desprenden las
siguientes hipótesis: 

1\. Se plantea la hipótesis de que el tamaño de la empresa está
relacionado por la posibilidad de sindicalización.

2\. Se plantea la hipótesis de que un mayor tamaño de empresa se
relaciona con mayores salarios.

3\. Se plantea la hipótesis de que el tamaño de empresa esta relacionado
a la formalidad laboral.
