---
title: "Resultados"
---

```{r}
# cargar datos
load("input/data-proc/proc_casen.Rdata")

# cargar librerías
pacman::p_load(tidyverse, # Manipulación datos
               sjPlot, # Gráficos y tablas
               sjmisc, # Descriptivos
               corrplot, # Correlaciones
               psych, # Test estadísticos
               kableExtra, # Tablas
               sjstats,
               haven,
               ggplot2,
               ggpubr,
               gtsummary,
               dplyr,
               stargazer,
               descr,
               table1,
               report)
```

## Analisis descriptivo

Resumen de las estadisticas descriptivas clave y visualizaciones de apoyo.

### Variable PYME

```{r}

promedios <- proc_casen %>%
  filter(!is.na(pertenece_sindicato)) %>%  # Excluir NAs
  group_by(pertenece_sindicato) %>%
  summarise(
    promedio_tamaño = mean(tamaño_empresa, na.rm = TRUE),
    n = n()
  ) %>%
  mutate(
    categoria = ifelse(pertenece_sindicato == 1, "Sí pertenece", "No pertenece"),
    etiqueta = paste0(round(promedio_tamaño, 1), "\n(n=", n, ")")
  )

ggplot(promedios, aes(y = reorder(pertenece_sindicato, promedio_tamaño), 
                      x = promedio_tamaño)) +
  geom_col(fill = "steelblue", width = 0.7) +
  geom_text(aes(label = etiqueta), 
        hjust = -0.2, size = 3, fontface = "bold") +
  labs(title = "Promedio de tamaño de empresa por pertenencia a sindicato",
       y = "Pertenece a sindicato",
       x = "Tamaño promedio de empresa",
       caption = "Fuente: Elaboración propia en base a CASEN 2022") +
  theme_light() +
  theme(axis.text.y = element_text(size = 11, face = "bold"),
        plot.title = element_text(size = 14, face = "bold", hjust = 0.5)) +
  scale_x_continuous(expand = expansion(mult = c(0, 0.1))) # Espacio para el texto


```



## Analisis bivariado

### Hipotesis 1: el tamaño de la empresa está relacionado por la posibilidad de sindicalización.

```{r}
t.test(proc_casen$tamaño_empresa ~ proc_casen$pertenece_sindicato, alternative = "less") %>% report()
```

```{r}
chiqtest <- chisq.test(proc_casen$pyme, proc_casen$pertenece_sindicato)
n <- na.omit(proc_casen %>% select(pyme, pertenece_sindicato)) %>% nrow()
cramer <- sqrt(chiqtest$statistic / n*(2-1))
cramer 
report(chiqtest)

```

```{r}
matriz <- proc_casen %>% select(pyme, pertenece_sindicato) # creamos matriz con var de interes

tetrachoric(matriz, na.rm = T)
```

```{r}
cor.test(proc_casen$pertenece_sindicato, proc_casen$tamaño_empresa)
```

### Hipotesis 2:

```{r}
cor.test(proc_casen$pertenece_sindicato, proc_casen$salario)

t.test(proc_casen$salario ~ proc_casen$pertenece_sindicato, alternative = "less") %>% report()
```

### hipotesis 3

```{r}
chiqtest <- chisq.test(proc_casen$pyme, proc_casen$formalidad)
n <- na.omit(proc_casen %>% select(pyme, formalidad)) %>% nrow()
cramer <- sqrt(chiqtest$statistic / n*(2-1))
cramer 
report(chiqtest)

cor.test(proc_casen$pertenece_sindicato, proc_casen$formalidad)
```
