---
title: "Referencias"
---

Ahumada, J. M., y Sossdorf, F. (2017). *Equidad social y transformación
de la estructura productiva en Chile. Ensayos para un modelo de
desarrollo sostenible*: Un cambio estructural, 65-126.

Durán, G. (2024). Negociación colectiva, recursos de poder y resultados
distributivos. El caso de los Consejos de Salarios en Uruguay.
*Cuadernos de Relaciones Laborales*, 43(1), 129-148.

Espro, M., Zorattani, D. (2012). La miseria de las Pymes. Pobreza y
desarrollo en la Argentina reciente. *Seminario "Mercado de Trabajo,
distribución del Ingreso y pobreza en la Argentina de la
post-convertibilidad. Balances y perspectivas"*, CEPED-FCE-UBA y
CEyDS-IIGG-FCS-UBA

Espro, M. y Baez, J. (2018). Plusvalía extraordinaria por pobreza en
Argentina. *Jornadas de Economía Crítica*, Universidad del Litoral.

Gárate, M. (2012). *La revolución capitalista de Chile* (1973-2003).
Editorial Alberto Hurtado.

Iñigo Carrera, J. (2013). *El capital: razón histórica, sujeto
revolucionario y conciencia*. Imago Mundi.

Marx, K. (2010). *El Capital. Crítica de la Economía Políticaa.* LOM
ediciones.

Núñez, D., Silva, I., Mella, E., Ahumada, J. M., Cataldo, C.,
Cataldo-Estay, T., Moreau, A., Guzmán, I., Navarrete, B., Gutiérrez, G.,
& Robert, V. (2025). *Apuntes para superar el neoliberalismo: rutas para
un nuevo modelo de desarrollo para Chile*. América en Movimiento.

Organización Internacional del Trabajo. (2015). *Recomendación sobre la
transición de la economía informal a la economía formal (núm. 204)*.
Conferencia Internacional del Trabajo, 104.ª reunión.
<https://www.ilo.org/wcmsp5/groups/public/---ed_norm/---relconf/documents/meetingdocument/wcms_377774.pdf>

Ruiz, C. (2013). *Conflicto social en el neoliberalismo avanzado:
análisis de clase de la revuelta estudiantil en Chile*. CLACSO, primera
edición. Ciudad Autónoma de Buenos Aires, Argentina.
